#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")"

PROJECT_ROOT="$(cd .. && pwd)"
MODE="${1:-auto}"
MODEL_ONLY_DURATION_SEC="${2:-${DURATION_SEC:-25}}"
RUN_ID="${RUN_ID:-$(date +%Y%m%d_%H%M%S)}"
PYTHON_BIN="${PYTHON_BIN:-/home/lavine/miniconda3/envs/fcreal/bin/python}"
MPLCONFIGDIR="${MPLCONFIGDIR:-/tmp/matplotlib}"
CONTACT_TURNING_OVERLAY_CONFIG="${CONTACT_TURNING_OVERLAY_CONFIG:-config/g1/g1_29dof_with_hand_valve_contact_turning_overlay.yaml}"
MARKER_FILE="${MARKER_FILE:-/tmp/falcon_valve_contact_turning_markers_${RUN_ID}.json}"
LOG_FILE="${LOG_FILE:-${PROJECT_ROOT}/artifacts/demo_logs/valve_contact_turning_${RUN_ID}.csv}"
SIM_STATUS_FILE="${SIM_STATUS_FILE:-/tmp/falcon_valve_contact_turning_status_${RUN_ID}.json}"
SIM_CONTROL_FILE="${SIM_CONTROL_FILE:-/tmp/falcon_valve_contact_turning_control_${RUN_ID}.json}"
SIM_STARTUP_WAIT_SEC="${SIM_STARTUP_WAIT_SEC:-1.5}"
ELASTIC_LENGTH="${ELASTIC_LENGTH:--0.15}"
ELASTIC_RELEASE_DELAY_AFTER_POLICY_START_SEC="${ELASTIC_RELEASE_DELAY_AFTER_POLICY_START_SEC:-1.2}"
# 接触转阀门会在策略启动后立刻移动右臂。这里给下肢策略多留一点站稳时间，
# 避免有效抓取测试被初始倒地或大倾角污染。
TRACKING_START_DELAY_SEC="${TRACKING_START_DELAY_SEC:-3.2}"

# strictXX 用于单目标工作区间测试，不改默认展示序列。
# 示例：bash sim2real/launch_valve_contact_turning_7dof_with_hand_auto.sh strict60
SINGLE_TURN_PRESET_TARGET_DEG=""
case "${MODE}" in
  strict10|strict20|strict30|strict45|strict60|strict75|strict90|strict120)
    SINGLE_TURN_PRESET_TARGET_DEG="${MODE#strict}"
    MODE="auto"
    ;;
esac

if [[ -n "${SINGLE_TURN_PRESET_TARGET_DEG}" ]]; then
  VALVE_TURN_TARGET_SEQUENCE_DEG="${VALVE_TURN_TARGET_SEQUENCE_DEG:-${SINGLE_TURN_PRESET_TARGET_DEG}}"
  VALVE_TURN_SPEED_DEG="${VALVE_TURN_SPEED_DEG:-0.9}"
  VALVE_TURN_SEGMENT_SETTLE_ENABLED="${VALVE_TURN_SEGMENT_SETTLE_ENABLED:-1}"
  VALVE_TURN_SEGMENT_SETTLE_ERROR_DEG="${VALVE_TURN_SEGMENT_SETTLE_ERROR_DEG:-2.0}"
  VALVE_TURN_SEGMENT_SETTLE_VEL_DEG_S="${VALVE_TURN_SEGMENT_SETTLE_VEL_DEG_S:-2.0}"
  VALVE_TURN_SEGMENT_SETTLE_SEC="${VALVE_TURN_SEGMENT_SETTLE_SEC:-0.8}"
  VALVE_TURN_SEGMENT_SETTLE_MAX_SEC="${VALVE_TURN_SEGMENT_SETTLE_MAX_SEC:-35.0}"
  # 严格单目标展示用稳定三点包络：掌心 + 拇指 + 至少一根手指。
  # 不强制食指和中指同时持续接触，避免中指短暂丢接触把可用抓握误判为失败。
  VALVE_GRASP_SUCCESS_REQUIRE_INDEX="${VALVE_GRASP_SUCCESS_REQUIRE_INDEX:-0}"
  VALVE_GRASP_SUCCESS_REQUIRE_MIDDLE="${VALVE_GRASP_SUCCESS_REQUIRE_MIDDLE:-0}"
  VALVE_TURN_COMPLETION_REQUIRE_GRASP="${VALVE_TURN_COMPLETION_REQUIRE_GRASP:-1}"
  VALVE_TURN_COMPLETION_MIN_CONTACT_HEALTH_RATIO="${VALVE_TURN_COMPLETION_MIN_CONTACT_HEALTH_RATIO:-0.75}"
  VALVE_TURN_COMPLETION_MAX_SLIP_M="${VALVE_TURN_COMPLETION_MAX_SLIP_M:-0.12}"
  VALVE_TURN_COMPLETION_TIMEOUT_IS_FAILURE="${VALVE_TURN_COMPLETION_TIMEOUT_IS_FAILURE:-1}"
  # 默认仍在 hold 阶段释放柔顺连接，用真实接触和 angle brake 检查最终保持质量。
  VALVE_CONTACT_ASSIST_RELEASE_ON_TURN_HOLD="${VALVE_CONTACT_ASSIST_RELEASE_ON_TURN_HOLD:-1}"
  VALVE_TURN_ENTRY_MAX_SLIP_M="${VALVE_TURN_ENTRY_MAX_SLIP_M:-0.045}"
  VALVE_TURN_ENTRY_MAX_CONTACT_FORCE_N="${VALVE_TURN_ENTRY_MAX_CONTACT_FORCE_N:-50}"
  case "${SINGLE_TURN_PRESET_TARGET_DEG}" in
    10|20) DURATION_SEC="${DURATION_SEC:-80}" ;;
    30|45) DURATION_SEC="${DURATION_SEC:-110}" ;;
    60|75) DURATION_SEC="${DURATION_SEC:-145}" ;;
    *) DURATION_SEC="${DURATION_SEC:-180}" ;;
  esac
else
  DURATION_SEC="${DURATION_SEC:-75}"
  VALVE_TURN_TARGET_SEQUENCE_DEG="${VALVE_TURN_TARGET_SEQUENCE_DEG:-10,-20,30}"
fi

VALVE_TURN_SPEED_DEG="${VALVE_TURN_SPEED_DEG:-}"
VALVE_TURN_SEGMENT_SETTLE_ENABLED="${VALVE_TURN_SEGMENT_SETTLE_ENABLED:-}"
VALVE_TURN_SEGMENT_SETTLE_ERROR_DEG="${VALVE_TURN_SEGMENT_SETTLE_ERROR_DEG:-}"
VALVE_TURN_SEGMENT_SETTLE_VEL_DEG_S="${VALVE_TURN_SEGMENT_SETTLE_VEL_DEG_S:-}"
VALVE_TURN_SEGMENT_SETTLE_SEC="${VALVE_TURN_SEGMENT_SETTLE_SEC:-}"
VALVE_TURN_SEGMENT_SETTLE_MAX_SEC="${VALVE_TURN_SEGMENT_SETTLE_MAX_SEC:-}"
VALVE_TURN_COMPLETION_REQUIRE_GRASP="${VALVE_TURN_COMPLETION_REQUIRE_GRASP:-}"
VALVE_TURN_COMPLETION_MIN_CONTACT_HEALTH_RATIO="${VALVE_TURN_COMPLETION_MIN_CONTACT_HEALTH_RATIO:-}"
VALVE_TURN_COMPLETION_MAX_SLIP_M="${VALVE_TURN_COMPLETION_MAX_SLIP_M:-}"
VALVE_TURN_COMPLETION_MAX_GRASP_ERROR_M="${VALVE_TURN_COMPLETION_MAX_GRASP_ERROR_M:-}"
VALVE_TURN_COMPLETION_TIMEOUT_IS_FAILURE="${VALVE_TURN_COMPLETION_TIMEOUT_IS_FAILURE:-}"
VALVE_CONTACT_ASSIST_RELEASE_ON_TURN_HOLD="${VALVE_CONTACT_ASSIST_RELEASE_ON_TURN_HOLD:-}"
VALVE_TURN_ENTRY_MAX_SLIP_M="${VALVE_TURN_ENTRY_MAX_SLIP_M:-}"
VALVE_TURN_ENTRY_MAX_CONTACT_FORCE_N="${VALVE_TURN_ENTRY_MAX_CONTACT_FORCE_N:-}"
VALVE_GRASP_SUCCESS_REQUIRE_INDEX="${VALVE_GRASP_SUCCESS_REQUIRE_INDEX:-}"
VALVE_GRASP_SUCCESS_REQUIRE_MIDDLE="${VALVE_GRASP_SUCCESS_REQUIRE_MIDDLE:-}"

# 序列展示里 base 靠近/yaw 调整属于正常全身补偿，只记录，不作为失败条件。
# 失败主要看是否摔倒、撞上阀门、手松开或接触异常。
VALVE_TURN_ABORT_MAX_BASE_APPROACH_M="${VALVE_TURN_ABORT_MAX_BASE_APPROACH_M:-0.0}"
VALVE_TURN_ABORT_MIN_BASE_TO_VALVE_X_M="${VALVE_TURN_ABORT_MIN_BASE_TO_VALVE_X_M:-0.0}"
VALVE_TURN_ABORT_MAX_BASE_YAW_DRIFT_DEG="${VALVE_TURN_ABORT_MAX_BASE_YAW_DRIFT_DEG:-0.0}"
VALVE_TURN_ABORT_BASE_TILT_DEG="${VALVE_TURN_ABORT_BASE_TILT_DEG:-25.0}"

rm -f "${MARKER_FILE}" "${SIM_STATUS_FILE}" "${SIM_CONTROL_FILE}"

start_background() {
  if command -v setsid >/dev/null 2>&1; then
    setsid env "$@" &
  else
    env "$@" &
  fi
  STARTED_PID="$!"
}

stop_background() {
  local pid="${1:-}"
  if [[ -z "${pid}" ]]; then
    return
  fi
  if ! kill -0 "${pid}" 2>/dev/null; then
    return
  fi
  kill -- "-${pid}" 2>/dev/null || kill "${pid}" 2>/dev/null || true
  sleep 0.2
  if kill -0 "${pid}" 2>/dev/null; then
    kill -9 -- "-${pid}" 2>/dev/null || kill -9 "${pid}" 2>/dev/null || true
  fi
  wait "${pid}" 2>/dev/null || true
}

cleanup() {
  local status=$?
  trap - EXIT INT TERM
  stop_background "${POLICY_PID:-}"
  stop_background "${SIM_PID:-}"
  exit "${status}"
}
trap cleanup EXIT INT TERM

mkdir -p "$(dirname "${LOG_FILE}")"

start_background \
  MPLCONFIGDIR="${MPLCONFIGDIR}" \
  PYTHON_BIN="${PYTHON_BIN}" \
  ELASTIC_LENGTH="${ELASTIC_LENGTH}" \
  EXTRA_OVERLAY_CONFIG="${CONTACT_TURNING_OVERLAY_CONFIG}" \
  MARKER_FILE="${MARKER_FILE}" \
  SIM_STATUS_FILE="${SIM_STATUS_FILE}" \
  SIM_CONTROL_FILE="${SIM_CONTROL_FILE}" \
  ./launch_valve_grasp_contact_7dof_with_hand_sim.sh
SIM_PID="${STARTED_PID}"

if [[ "${MODE}" == "--model-only" || "${MODE}" == "model-only" ]]; then
  echo "[VALVE_CONTACT_TURN] model-only viewer for ${MODEL_ONLY_DURATION_SEC}s"
  sleep "${MODEL_ONLY_DURATION_SEC}"
  exit 0
fi

sleep "${SIM_STARTUP_WAIT_SEC}"

start_background \
  MPLCONFIGDIR="${MPLCONFIGDIR}" \
  PYTHON_BIN="${PYTHON_BIN}" \
  AUTO_WORKFLOW=0 \
  AUTO_START_POLICY=1 \
  ELASTIC_RELEASE_DELAY_AFTER_POLICY_START_SEC="${ELASTIC_RELEASE_DELAY_AFTER_POLICY_START_SEC}" \
  TRACKING_START_DELAY_SEC="${TRACKING_START_DELAY_SEC}" \
  DURATION_SEC="${DURATION_SEC}" \
  VALVE_TURN_TARGET_SEQUENCE_DEG="${VALVE_TURN_TARGET_SEQUENCE_DEG}" \
  VALVE_TURN_SPEED_DEG="${VALVE_TURN_SPEED_DEG}" \
  VALVE_TURN_SEGMENT_SETTLE_ENABLED="${VALVE_TURN_SEGMENT_SETTLE_ENABLED}" \
  VALVE_TURN_SEGMENT_SETTLE_ERROR_DEG="${VALVE_TURN_SEGMENT_SETTLE_ERROR_DEG}" \
  VALVE_TURN_SEGMENT_SETTLE_VEL_DEG_S="${VALVE_TURN_SEGMENT_SETTLE_VEL_DEG_S}" \
  VALVE_TURN_SEGMENT_SETTLE_SEC="${VALVE_TURN_SEGMENT_SETTLE_SEC}" \
  VALVE_TURN_SEGMENT_SETTLE_MAX_SEC="${VALVE_TURN_SEGMENT_SETTLE_MAX_SEC}" \
  VALVE_TURN_COMPLETION_REQUIRE_GRASP="${VALVE_TURN_COMPLETION_REQUIRE_GRASP}" \
  VALVE_TURN_COMPLETION_MIN_CONTACT_HEALTH_RATIO="${VALVE_TURN_COMPLETION_MIN_CONTACT_HEALTH_RATIO}" \
  VALVE_TURN_COMPLETION_MAX_SLIP_M="${VALVE_TURN_COMPLETION_MAX_SLIP_M}" \
  VALVE_TURN_COMPLETION_MAX_GRASP_ERROR_M="${VALVE_TURN_COMPLETION_MAX_GRASP_ERROR_M}" \
  VALVE_TURN_COMPLETION_TIMEOUT_IS_FAILURE="${VALVE_TURN_COMPLETION_TIMEOUT_IS_FAILURE}" \
  VALVE_CONTACT_ASSIST_RELEASE_ON_TURN_HOLD="${VALVE_CONTACT_ASSIST_RELEASE_ON_TURN_HOLD}" \
  VALVE_TURN_ENTRY_MAX_SLIP_M="${VALVE_TURN_ENTRY_MAX_SLIP_M}" \
  VALVE_TURN_ENTRY_MAX_CONTACT_FORCE_N="${VALVE_TURN_ENTRY_MAX_CONTACT_FORCE_N}" \
  VALVE_GRASP_SUCCESS_REQUIRE_INDEX="${VALVE_GRASP_SUCCESS_REQUIRE_INDEX}" \
  VALVE_GRASP_SUCCESS_REQUIRE_MIDDLE="${VALVE_GRASP_SUCCESS_REQUIRE_MIDDLE}" \
  VALVE_TURN_ABORT_BASE_TILT_DEG="${VALVE_TURN_ABORT_BASE_TILT_DEG}" \
  VALVE_TURN_ABORT_MAX_BASE_APPROACH_M="${VALVE_TURN_ABORT_MAX_BASE_APPROACH_M}" \
  VALVE_TURN_ABORT_MIN_BASE_TO_VALVE_X_M="${VALVE_TURN_ABORT_MIN_BASE_TO_VALVE_X_M}" \
  VALVE_TURN_ABORT_MAX_BASE_YAW_DRIFT_DEG="${VALVE_TURN_ABORT_MAX_BASE_YAW_DRIFT_DEG}" \
  EXTRA_OVERLAY_CONFIG="${CONTACT_TURNING_OVERLAY_CONFIG}" \
  MARKER_FILE="${MARKER_FILE}" \
  LOG_FILE="${LOG_FILE}" \
  SIM_STATUS_FILE="${SIM_STATUS_FILE}" \
  SIM_CONTROL_FILE="${SIM_CONTROL_FILE}" \
  ./launch_valve_grasp_contact_7dof_with_hand_policy.sh
POLICY_PID="${STARTED_PID}"

echo "[VALVE_CONTACT_TURN] log=${LOG_FILE}"
echo "[VALVE_CONTACT_TURN] marker=${MARKER_FILE}"
wait "${POLICY_PID}"
POLICY_PID=""
